from django.contrib import admin
from .models import *
admin.site.register(Districts)
admin.site.register(Events)
admin.site.register(Favourites)
admin.site.register(GarbagePoints)
admin.site.register(Objects)
admin.site.register(Organizations)
admin.site.register(Rates)
admin.site.register(Reports)
admin.site.register(Results)
admin.site.register(Roles)
admin.site.register(Route)
admin.site.register(SexDic)
admin.site.register(Users)
admin.site.register(WasteTypes)
admin.site.register(Admarea)
admin.site.register(AuthGroup)
admin.site.register(AuthGroupPermissions)
admin.site.register(AuthPermission)
admin.site.register(AuthUser)
admin.site.register(AuthUserGroups)
admin.site.register(AuthUserUserPermissions)
admin.site.register(Difictulites)
admin.site.register(DjangoAdminLog)
admin.site.register(DjangoContentType)
admin.site.register(DjangoMigrations)
admin.site.register(DjangoSession)
admin.site.register(EventsOnObjects)
admin.site.register(EventsOnRoutes)
admin.site.register(Permission)
admin.site.register(PointTypes)
admin.site.register(RoleOnPermission)
admin.site.register(Statuses)
admin.site.register(StatusesR)
admin.site.register(UserHasRole)
admin.site.register(WorkingHours)
# Register your models here.
