# Generated by Django 4.2 on 2023-05-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0003_rename_statusesrdict_statusesevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='eco.statusesevent'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='status_id_r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to='eco.statusesreport'),
        ),
    ]
