# Generated by Django 4.1.4 on 2023-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0004_alter_events_status_id_alter_reports_status_id_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='natureobjects',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='nature_objects/'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='routes/'),
        ),
        migrations.AlterField(
            model_name='sortpoints',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sort_points/'),
        ),
    ]
