# Generated by Django 4.1.4 on 2023-06-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eco", "0005_alter_customuser_photo_alter_events_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="point_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eco.sortpoints",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="nature_objects",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="eco.natureobjects"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="routes",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="eco.routes"
            ),
        ),
    ]
