# Generated by Django 4.1.4 on 2023-06-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eco", "0006_reports_point_id_alter_events_nature_objects_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={"ordering": ("-pk",)},
        ),
        migrations.AlterModelOptions(
            name="natureobjects",
            options={"ordering": ("-pk",)},
        ),
        migrations.AlterModelOptions(
            name="sortpoints",
            options={"ordering": ("-pk",)},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="locality",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="user/"),
        ),
    ]
