# Generated by Django 4.1.4 on 2023-06-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eco", "0007_alter_events_options_alter_natureobjects_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="natureobjects",
            name="category_obj_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nature_objects",
                to="eco.categoryobjdict",
            ),
            preserve_default=False,
        ),
    ]
