# Generated by Django 4.1.4 on 2023-06-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eco", "0008_alter_natureobjects_category_obj_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="natureobjects",
            name="schedule",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sortpoints",
            name="schedule",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
