# Generated by Django 4.1.4 on 2023-07-10 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("eco", "0010_alter_customuser_photo_alter_events_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourites",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
