# Generated by Django 4.1.4 on 2023-07-14 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eco", "0011_favourites_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favourites",
            options={"ordering": ("-pk",)},
        ),
        migrations.RemoveIndex(
            model_name="favourites",
            name="eco_favouri_content_a7618a_idx",
        ),
    ]
