# Generated by Django 4.1.4 on 2023-11-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eco", "0012_alter_favourites_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, max_length=3000, upload_to="user/"),
        ),
        migrations.AlterField(
            model_name="events",
            name="photo",
            field=models.ImageField(blank=True, max_length=3000, upload_to="events/"),
        ),
        migrations.AlterField(
            model_name="natureobjects",
            name="photo",
            field=models.ImageField(
                blank=True, max_length=3000, upload_to="nature_objects/"
            ),
        ),
        migrations.AlterField(
            model_name="reports",
            name="photo",
            field=models.ImageField(blank=True, max_length=3000, upload_to="reports/"),
        ),
        migrations.AlterField(
            model_name="routes",
            name="photo",
            field=models.ImageField(blank=True, max_length=3000, upload_to="routes/"),
        ),
        migrations.AlterField(
            model_name="sortpoints",
            name="photo",
            field=models.ImageField(
                blank=True, max_length=3000, upload_to="sort_points/"
            ),
        ),
    ]
