# Generated by Django 4.1.4 on 2023-12-17 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eco", "0013_alter_customuser_photo_alter_events_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="point_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="eco.sortpoints",
            ),
        ),
    ]
