# Generated by Django 4.1.4 on 2024-01-31 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eco", "0014_alter_reports_point_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="kind_of_activity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="not valid phone number!", regex="\\+?(?:7|8)9\\d{9}"
                    )
                ],
            ),
        ),
    ]
